### ISSUE TITLE
Task 6

### ISSUE THREAD

**Issue by TeeMan508** [TeeMan508/SiriusCpp#4]
Добавил 6-ое задание

**Comment by dzheltkov** [comment]
Пока не разобрался, в чём дело, но на простейшем примере `"+ [1 2 3] [4 5 6]"` вылетает с ошибкой
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
```

Кроме того, при компиляции есть следующие предупреждения:
```
SiriusCpp/Task6/polynom.cpp: In member function 'void polynom::calculate(std::string)':
SiriusCpp/Task6/polynom.cpp:108:19: warning: unknown escape sequence: '\+'
  108 |                   "([\\d\\s\{\}\,]*)"
      |                   ^~~~~~~~~~~~~~~~~~~
SiriusCpp/Task6/polynom.cpp:108:19: warning: unknown escape sequence: '\*'
SiriusCpp/Task6/polynom.cpp:108:19: warning: unknown escape sequence: '\}'
SiriusCpp/Task6/polynom.cpp:108:19: warning: unknown escape sequence: '\,'

**Comment by TeeMan508** [comment]
Ошибка возникает из-за того, что я сделал запись полиномов через фигурные скобки, таким образом, выражение, которое вы использовали как пример, запишется в виде "+ {1 2 3} {4 5 6}". Предупреждения связаны с синтаксисом регулярных выражений. Вроде я верно записал выражение, так что, можно не обращать на них внимания.

**Comment by dzheltkov** [comment]
Записали немного неверно (то есть в итоге на результат это не влияет, но тем не менее).
То есть следовало записать примерно так:
"([\\d\\s\\{\\}\\,]*)"
Потому что иначе он воспринимает в записанной строке символ `\` как спецсимвол, чтобы строка содержала непосредственно нужный символ,  нужно писать `\\`.
Задание зачтено.
