### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by TeeMan508** [TeeMan508/SiriusCpp#5]
Добавил 7-ое задание

**Comment by dzheltkov** [comment]
У вас сейчас на каждой итерации несколько раз считается произведение матрицы на вектор.
Это, как правио, самая сложная операция, при этом достаточно на итерации один раз умножать на матрицу и один раз умножать на транспонированную.
Модифицируйте код, чтобы на итерации происходило по одному умножению на матрицу и на транспонированную.

**Comment by TeeMan508** [comment]
Поправил первое замечание, по второму замечанию не совсем понятно, как в функцию передать шаблон класса матриц. Матрица А вроде как и так передается как элемент шаблонного класс.

**Comment by dzheltkov** [comment]
Примерно так:
```
template <class UserMatrix>
Matrix<Type> solve(const UserMatrix& A, Matrix<Type> B, Matrix<Type> X0){
...
}
```
или так
```
template <template class UserMatrix>
Matrix<Type> solve(const UserMatrix<Type>& A, Matrix<Type> B, Matrix<Type> X0){
...
}
```
если хотите, чтобы пользовательская матрица тоже зависила от шаблона Type.

Кстати, функция `solve` никак не использует объект класса, поэтому её стоит или сделать статической, или вообще объявить в классе дружественной, а саму сделать вне класса.

Кроме того, `Matrix<Type>` лучше передавать в матрицу по константной ссылке.

**Comment by TeeMan508** [comment]
Поправил

**Comment by dzheltkov** [comment]
Задание зачтено.
